[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    miguelbalboa/MFRC522 @ ^1.4.11
    adafruit/Adafruit BME680 Library @ ^2.0.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit BusIO @ ^1.16.1
    knolleary/PubSubClient @ ^2.8